### ISSUE TITLE
Travis badge points to old repository

### ISSUE THREAD

**Issue by palfrey** [lilyball/rust-lua#31]
The badge in the README points to https://travis-ci.org/kballard/rust-lua not https://travis-ci.org/lilyball/rust-lua

**Comment by lilyball** [comment]
Thanks, I just fixed it. This repo is pretty old so I'm surprised anyone is even still looking at it.

**Comment by palfrey** [comment]
This repo was mentioned in https://github.com/rust-unofficial/awesome-rust and I've been going through and doing cleanup work there recently, so spotted this along the way :)
